In [1]:
import pandas as pd
import numpy as np

In [2]:
# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

In [ ]:
def max_employment(countries, employment):
    '''
    Fill in this function to return the name of the country
    with the highest employment in the given employment
    data, and the employment in that country.
    '''
    max_country = None      # Replace this with your code
    max_value = 0   # Replace this with your code
    for i in range(len(countries)):
        country = countries[i]
        print(country)
        print(i)
        country_employment = employment[i]
        if(country_employment > max_value):
            max_country = countries[i]
            max_value = employment[i]   # Replace this with your code

    return (max_country, max_value)
    

In [35]:
def standardize_data(values):
    '''
    Fill in this function to return a standardized version of the given values,
    which will be in a NumPy array. Each value should be translated into the
    number of standard deviations that value is away from the mean of the data.
    (A positive number indicates a value higher than the mean, and a negative
    number indicates a value lower than the mean.)
    '''
    return (values - values.mean()) / values.std()

In [4]:
my_mean = employment.mean()

In [6]:
print(my_mean)
print(employment - my_mean)

58.6850000385
[ -2.98499928  -7.28499851  -8.18500004  17.01499691  -0.28499851
 -18.58500157   2.81499996  -1.58500157   2.21500149   7.91499843
   1.71500149   9.41499843   8.21500149  -5.28499851 -10.08500157
  -1.8850008   12.91499843  -0.28499851  11.71500149 -17.48499928]


In [7]:
values = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
my_mean = values.mean()
my_std = values.std()
print(my_mean)
print(my_std)

4.5
2.87228132327


In [33]:
(values - my_mean) / my_std

array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
        0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ])

In [36]:
standardize_data(values)

array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
        0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ])

In [12]:
(10.5/100) - (3.7/100)

0.06799999999999999

In [24]:
(3.7) - (10.5)

-6.8

In [34]:
((62.3/100) - (58.6/100))/ (10.5/100)

0.3523809523809527

In [32]:
((0.03700000000000003*100) - (10.5/100))/100

0.03595000000000003

In [37]:
# Time spent in the classroom in the first week for 20 students
time_spent = np.array([
       12.89697233,    0.        ,   64.55043217,    0.        ,
       24.2315615 ,   39.991625  ,    0.        ,    0.        ,
      147.20683783,    0.        ,    0.        ,    0.        ,
       45.18261617,  157.60454283,  133.2434615 ,   52.85000767,
        0.        ,   54.9204785 ,   26.78142417,    0.
])

# Days to cancel for 20 students
days_to_cancel = np.array([
      4,   5,  37,   3,  12,   4,  35,  38,   5,  37,   3,   3,  68,
     38,  98,   2, 249,   2, 127,  35
])

In [51]:
"""
Your code returned 30.0.
The expected answer was 25.0.
"""
time_spent = np.array([10, 10, 10, 20, 20, 20, 30, 30, 30])
days_to_cancel = np.array([6, 6, 6, 7, 7, 7, 8, 8, 8])

In [68]:
def mean_time_for_paid_students(time_spent, days_to_cancel):
    '''
    Fill in this function to calculate the mean time spent in the classroom
    for students who stayed enrolled at least (greater than or equal to) 7 days.
    Unlike in Lesson 1, you can assume that days_to_cancel will contain only
    integers (there are no students who have not canceled yet).
    
    The arguments are NumPy arrays. time_spent contains the amount of time spent
    in the classroom for each student, and days_to_cancel contains the number
    of days until each student cancel. The data is given in the same order
    in both arrays.
    '''
    return time_spent[days_to_cancel >= 7].mean()

In [44]:
#time_spent[days_to_cancel[days_to_cancel > 7]]
arr_bool = days_to_cancel > 7


In [58]:
time_spent.size

9

In [48]:
time_spent.mean()

37.972997983500001

In [69]:
mean_time_for_paid_students(time_spent, days_to_cancel)

25.0

In [61]:
aux = days_to_cancel > 7

In [62]:
aux

array([False, False, False, False, False, False,  True,  True,  True], dtype=bool)

In [65]:
time_spent[aux].sum()

90

In [67]:
time_spent[aux].sum()/time_spent.size

10.0

In [174]:
countries = ['Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda',
             'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
             'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
             'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia']

life_expectancy_values = [74.7,  75. ,  83.4,  57.6,  74.6,  75.4,  72.3,  81.5,  80.2,
                          70.3,  72.1,  76.4,  68.1,  75.2,  69.8,  79.4,  70.8,  62.7,
                          67.3,  70.6]

gdp_values = [ 1681.61390973,   2155.48523109,  21495.80508273,    562.98768478,
              13495.1274663 ,   9388.68852258,   1424.19056199,  24765.54890176,
              27036.48733192,   1945.63754911,  21721.61840978,  13373.21993972,
                483.97086804,   9783.98417323,   2253.46411147,  25034.66692293,
               3680.91642923,    366.04496652,   1175.92638695,   1132.21387981]

# Life expectancy and gdp data in 2007 for 20 countries
life_expectancy = pd.Series(life_expectancy_values)
gdp = pd.Series(gdp_values)

In [160]:
# My definition
"""
def variable_correlation(variable1, variable2):
    vbool1 = variable1 > variable1.mean()
    vbool2 = variable2 > variable2.mean()
    num_same_direction = len(variable1[vbool1 == vbool2])        # Replace this with your code
    num_different_direction = len(variable1[vbool1 != vbool2])   # Replace this with your code
    return (num_same_direction, num_different_direction)
"""

In [176]:
# Udacity definition
def variable_correlation(variable1, variable2):

    # Avaliando se a variable1 and variable2 estão acima da média
    both_above = (variable1 > variable1.mean()) & \
                 (variable2 > variable2.mean())
    
    # Avaliando se a variable1 and variable2 estão abaixo da média
    both_below = (variable1 < variable1.mean()) & \
                 (variable2 < variable2.mean())
        
    # Criando um array de boolean 
    is_same_direction = both_above | both_below    
    
    # Retornando o total da correlação direta
    num_same_direction = is_same_direction.sum()
    
    # Retornando o total da correlação inversa
    num_different_direction = len(variable1) - num_same_direction
    return (num_same_direction, num_different_direction)    

In [169]:
v1 = pd.Series([1, 2, 3, 4])
#v2 = pd.Series([4, 5, 6, 7])
v2 = pd.Series([7, 6, 5, 4])

In [156]:
vbool1 = v1 > v1.mean()
vbool2 = v2 > v2.mean()

In [158]:
len(v1[vbool1 == vbool2])

0

In [177]:
r1, r2 = variable_correlation(life_expectancy,gdp)

In [178]:
print(r1,r2)

17 3


In [180]:
v1.describe()

count    4.000000
mean     2.500000
std      1.290994
min      1.000000
25%      1.750000
50%      2.500000
75%      3.250000
max      4.000000
dtype: float64

In [181]:
countries = [
    'Afghanistan', 'Albania', 'Algeria', 'Angola',
    'Argentina', 'Armenia', 'Australia', 'Austria',
    'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
    'Barbados', 'Belarus', 'Belgium', 'Belize',
    'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
]


employment_values = [
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076,
]

# Employment data in 2007 for 20 countries
employment = pd.Series(employment_values, index=countries)

In [188]:
def max_employment(employment):
    '''
    Fill in this function to return the name of the country
    with the highest employment in the given employment
    data, and the employment in that country.
    
    The input will be a Pandas series where the values
    are employment and the index is country names.
    
    Try using the Pandas idxmax() function. Documention can
    be found here:
    http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.idxmax.html
    '''
    max_country = employment.argmax()      # Replace this with your code
    max_value = employment.loc[max_country]   # Replace this with your code

    return (max_country, max_value)

In [187]:
print(employment.loc[employment.argmax()] )

75.69999695


In [186]:
employment.loc['Armenia']

40.099998470000003

In [189]:
r1, r2 = max_employment(employment)

In [190]:
print(r1,r2)

Angola 75.69999695


In [227]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['c', 'd', 'e', 'f'])
soma = s1.add(s2,fill_value=0)

In [228]:
soma

a     1.0
b     2.0
c    13.0
d    24.0
e    30.0
f    40.0
dtype: float64

In [226]:
"""
#s1.loc['a']
for indice in soma.index:
    #print(indice)
    if soma.loc[indice] > 0:
        print(indice,soma.loc[indice])
    else: 
        if s1.loc[indice] > 0:
            print(indice,s1.loc[indice])
        else:
            print(indice,s2.loc[indice])
    
#retorno = soma.loc[soma.index] if soma.loc[soma.index] > 0 else (s1.loc[soma.index] | s2.loc[soma.index])
"""

"\n#s1.loc['a']\nfor indice in soma.index:\n    #print(indice)\n    if soma.loc[indice] > 0:\n        print(indice,soma.loc[indice])\n    else: \n        if s1.loc[indice] > 0:\n            print(indice,s1.loc[indice])\n        else:\n            print(indice,s2.loc[indice])\n    \n#retorno = soma.loc[soma.index] if soma.loc[soma.index] > 0 else (s1.loc[soma.index] | s2.loc[soma.index])\n"

In [229]:
names = pd.Series([
    'Andre Agassi',
    'Barry Bonds',
    'Christopher Columbus',
    'Daniel Defoe',
    'Emilio Estevez',
    'Fred Flintstone',
    'Greta Garbo',
    'Humbert Humbert',
    'Ivan Ilych',
    'James Joyce',
    'Keira Knightley',
    'Lois Lane',
    'Mike Myers',
    'Nick Nolte',
    'Ozzy Osbourne',
    'Pablo Picasso',
    'Quirinus Quirrell',
    'Rachael Ray',
    'Susan Sarandon',
    'Tina Turner',
    'Ugueth Urbina',
    'Vince Vaughn',
    'Woodrow Wilson',
    'Yoji Yamada',
    'Zinedine Zidane'
])

In [236]:
def reverse_names(names):
    '''
    Fill in this function to return a new series where each name
    in the input series has been transformed from the format
    "Firstname Lastname" to "Lastname, FirstName".
    
    Try to use the Pandas apply() function rather than a loop.
    '''
    return names.split()[1] + ', ' + names.split()[0]

In [238]:
new_name = names.apply(reverse_names)

In [239]:
new_name

0             Agassi, Andre
1              Bonds, Barry
2     Columbus, Christopher
3             Defoe, Daniel
4           Estevez, Emilio
5          Flintstone, Fred
6              Garbo, Greta
7          Humbert, Humbert
8               Ilych, Ivan
9              Joyce, James
10         Knightley, Keira
11               Lane, Lois
12              Myers, Mike
13              Nolte, Nick
14           Osbourne, Ozzy
15           Picasso, Pablo
16       Quirrell, Quirinus
17             Ray, Rachael
18          Sarandon, Susan
19             Turner, Tina
20           Urbina, Ugueth
21            Vaughn, Vince
22          Wilson, Woodrow
23             Yamada, Yoji
24         Zidane, Zinedine
dtype: object